### ISSUE TITLE
Log formatting + improvements

### ISSUE THREAD

**Issue by vmarcella** [Azure/InnovationEngine#39]
```[tasklist]
### Tasks
- [ ] Formatting improvements. Right now the formatting for the logs make the log messages too dense and hard to visually parse.
- [ ] Capturing the std out & err from command execution within the logs.
- [ ] Better formatting for listing out the steps that will be executed within the logs
```
